### PR TITLE
feat: Add autoleave feature (disabled)

### PR DESCRIPTION
**Pull request by freehuntx**
First of all: I love this project <3
Its awesome to not need an own server and being able to create cool games with it! Thanks alot!

I thought it might be nice to add functionality to automatically remove people who leave the page. What are your thoughts on it?

### CODE REVIEW

**Comment by dmotz** [comment]
Thanks for trying out Trystero! This is an interesting idea but the actions performed by `leave()` will happen anyway when the browser tab closes, so I don't think we need to add this.

**Comment by freehuntx** [comment]
Hmm weird. For me it always takes about 10-15 seconds for the other peer to really disconnect from my room. But i can just add this autoleave to my own wrapper ^^

**Comment by dmotz** [comment]
Which strategy are you using? (e.g. torrent)

**Comment by freehuntx** [comment]
Bittorrent. On the demo page i can see it happen. Open it in 2 windows. Close one window -> you have to wait some time until the disconnect happens. (Firefox & Chrome tested)

**Comment by dmotz** [comment]
@freehuntx I experimented with this approach and it ended up being a nice solution — more reliable than the connection close events in Firefox. It's been added in the latest release. Thanks for suggesting.

**Pull request closed without merging**
