### PR TITLE
Add awesome-trystero link to README

### PR DESCRIPTION
**Pull request by jeremyckahn**
Hello! I'd like to see Trystero's community grow and flourish, so I've started [awesome-trystero](https://github.com/jeremyckahn/awesome-trystero). It's a (currently small) list of projects using Trystero, but I'm planning to add to it more as I find new projects that use it.

### CODE REVIEW

**Comment by dmotz** [comment]
Nice! Thank you.

**Comment by dmotz** [comment]
@jeremyckahn By the way, if you're up for it, try testing `trystero@next` in your projects so I can start to get a sense of how it works for other community devs. The API is the same with the exception that Nostr is now the default strategy (since it has vastly more public relays versus WebTorrent). Among other improvements, connection times should be noticeably faster, but there are likely issues remaining to be worked out. Thanks!

**Comment by dmotz** [comment]
Thanks for taking the time to try it @jeremyckahn! Clearly still plenty of kinks to work out... Out of curiosity, which browser were you testing in?

**Comment by jeremyckahn** [comment]
> Out of curiosity, which browser were you testing in?

I was using Firefox 124 and Chromium 123 on Ubuntu 22.04. Data connections seemed to work fine, but video streams did not work.

**Pull request merged**
